node_addr = "http://blockchain-node:4467"
database_url = "postgresql://postgres:postgres@db/postgres"
# "rewards"    - load all rewards 
# "full"       - load all rewards & challenges 
# "filters"    - load only rewards or challenges associated with accounts or gateways 
#								 listed below in filters

mode = "filters"


# "true" or "false" 
# If set to "true", scan the node for the oldest block it has and start loading transactions from there. 
# If set to "false", start loading blocks starting at the current height of the node.
backfill = "true"

[log]
log_dir = "/opt/etl-lite"
